### DISCUSSION TITLE
0.1.5

### DISCUSSION THREAD

**Discussion by jgwill** [jgwill/jghfmanager#7] [Announcements]
1. Inferencer booting and executing the HuggingFace Endpoint described in the 'orpheus-config.yml'

```sh
pip install -U jghfmanager orpheuspypractice

#run 
cd mycreation_folder

ohfi
```

## Config

```yml
huggingface:
  name: chatmusician-myendpointname
  namespace: myusername
  repository: m-a-p/ChatMusician
  token_env_var: HUGGINGFACE_API_KEY
```

## Musical Inference request

```yml
musical:
  name: mycreationname
  sname: iterationname
  prompts:
    prompt1: "the prompt text...."
    prompt2: "another prompt or a variation...."
```

<hr /><em>This discussion was created from the release <a href='https://github.com/jgwill/jghfmanager/releases/tag/0.1.5'>0.1.5</a>.</em>
