### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by jgwill** [jgwill/jghfmanager#2]

**Comment by jgwill** [comment]
```yaml
huggingface:
  name: chatmusician-jgwill
  namespace: jgwill
  repository: m-a-p/ChatMusician
  token_env_var: HUGGINGFACE_API_KEY
```
