### ISSUE TITLE
Creative Requests YAML

### ISSUE THREAD

**Issue by jgwill** [jgwill/jghfmanager#3]
```yaml

musical_pieces:
  cname: Viva
  cfx: 21b
  cp:
    i1: "Develop a musical piece named Viva using the given chord progression. 'Am', 'Bm', 'Em', 'Bm', 'C', 'D', 'G'"
    i2: "Develop a musical piece named Viva using the given chord progression. 'Am', 'F#', 'Bm', 'Em', 'Am', 'F#', 'D', 'G'"
    i2b: "Craft a musical works named Viva that follow the given chord alternations. 'Am', 'F#', 'Bm', 'Em', 'Am', 'F#', 'D', 'G'"
    i2c: "Craft a musical works that follow the given chord. 'Am', 'Bm', 'Em', 'Bm', 'C'"
    i3: "Craft a musical works named Viva that follow the given chord alternations. 'Am', 'F#', 'Bm', 'Em', 'Am', 'F#', 'D', 'G'"
    i4: "Develop a basic chord alternation pattern that follow the given chord alternations 'Am', 'Bm', 'Em', 'Bm', 'C', 'D', 'G'"
    i4b: "Develop a basic chord progression and resolution pattern that follow the given chord 'Am', 'Bm', 'Em', 'Bm', 'C', 'D', 'G'"
    i4c: "Develop a basic chord progression and resolution pattern that follow the given chord 'Bm', 'Am', 'F#', 'Bm', 'Em'"
    i4c2: "Develop a basic chord progression and resolution pattern that follow the given chord 'Bm', 'Am', 'F#', 'Bm', 'Em'"
    i4c3: "Develop a basic chord progression and resolution pattern that follow the given chord 'Am' 'F#' 'Bm' 'Em'"
    i5: "Develop a basic chord progression pattern that follow the given chord 'Am', 'Bm', 'Em', 'Bm', 'C', 'D', 'G'"
    i6: "Develop a basic chord progression pattern that follow the given chord 'Am', 'F#', 'Bm', 'Em', 'Am', 'F#', 'D', 'G'"
    i7: "Develop a basic chord progression and resolution pattern that follow the given chord 'Am', 'F#', 'Bm', 'Em', 'Am', 'F#', 'D', 'G'"
    i8: "Develop a musical work based on 'Am', 'Bm', 'Em', 'Bm', 'C', 'D', 'G', 'Am', 'F#', 'Bm', 'Em', 'Am', 'F#', 'D', 'G'"
```

**Comment by jgwill** [comment]
```yaml

musical:
  name: Viva
  sname: 21b
  notes: prompts samples with degree
  prompts:
    deg1: "Develop a musical piece "

```
